-- =============================================================================
-- Migration 001 — Bronze Layer (Medallion Architecture)
-- Table: fact_raw_events
-- Strategy: Extract-Load (EL). Append-only, immutable, schema-free payload.
-- =============================================================================

-- Enable the uuid-ossp extension once per database
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Bronze table
-- Receives events from all 12 source systems as-is.
-- event_id is generated server-side (never from the client) to guarantee
-- global uniqueness and enable idempotent reprocessing.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_raw_events (
    event_id    UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
    source      VARCHAR(50)  NOT NULL,
    event_type  VARCHAR(100) NOT NULL,
    payload     JSONB        NOT NULL DEFAULT '{}',
    ingested_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed   BOOLEAN      NOT NULL DEFAULT FALSE  -- ETL orchestration flag
);

-- -----------------------------------------------------------------------------
-- Comments — self-documenting for Power BI / data team
-- -----------------------------------------------------------------------------
COMMENT ON TABLE  fact_raw_events             IS 'Bronze layer — raw append-only event log from all source systems';
COMMENT ON COLUMN fact_raw_events.event_id    IS 'UUID v4 generated by the ingestion backend; primary key for deduplication';
COMMENT ON COLUMN fact_raw_events.source      IS 'Origin system: orders, crm, payments, salud, incidents, subscriptions, …';
COMMENT ON COLUMN fact_raw_events.event_type  IS 'Domain event name within source (e.g. order_placed, ticket_created)';
COMMENT ON COLUMN fact_raw_events.payload     IS 'Full event body in JSONB. Queried via ->> / -> operators in Silver views';
COMMENT ON COLUMN fact_raw_events.ingested_at IS 'UTC timestamp of server reception — set by backend, never by client';
COMMENT ON COLUMN fact_raw_events.processed   IS 'TRUE once the ETL pipeline has promoted the event to a Silver/Gold table';

-- =============================================================================
-- Index strategy
-- Goal: accelerate the three most common Power BI query patterns:
--   1. time-range scans  (WHERE ingested_at BETWEEN x AND y)
--   2. source filter     (WHERE source = 'crm')
--   3. combined filter   (WHERE source = 'orders' AND ingested_at > x)
--   4. JSON field access (payload ->> 'ticket_id' = ?)
-- =============================================================================

-- 1. Descending timestamp — Power BI "last N days" queries hit the newest pages
CREATE INDEX IF NOT EXISTS idx_fre_ingested_at
    ON fact_raw_events (ingested_at DESC);

-- 2. Source lookup — partition-like filtering per system
CREATE INDEX IF NOT EXISTS idx_fre_source
    ON fact_raw_events (source);

-- 3. Event type within a source (used by the views below)
CREATE INDEX IF NOT EXISTS idx_fre_event_type
    ON fact_raw_events (event_type);

-- 4. *** Most useful for Power BI *** Composite covering source + ingested_at.
--    Satisfies "give me all CRM events from the last 30 days" in one index scan.
CREATE INDEX IF NOT EXISTS idx_fre_source_ingested
    ON fact_raw_events (source, ingested_at DESC);

-- 5. Composite for ETL orchestration (unprocessed events per source)
CREATE INDEX IF NOT EXISTS idx_fre_processed_source
    ON fact_raw_events (processed, source)
    WHERE processed = FALSE;

-- 6. GIN index for arbitrary JSONB field extraction
--    Accelerates: payload @> '{"customer_id":"C-123"}'
--    and: WHERE payload ->> 'priority' = 'high'  (if query planner uses it)
CREATE INDEX IF NOT EXISTS idx_fre_payload_gin
    ON fact_raw_events USING GIN (payload);

-- =============================================================================
-- Rollback
-- =============================================================================
-- DROP TABLE IF EXISTS fact_raw_events CASCADE;
