import uuid
from datetime import datetime
from sqlalchemy.orm import Session
from app.models import RawEvent
from app.schemas import EventCreate


def create_event(
    db: Session,
    event: EventCreate,
    event_id: uuid.UUID,
    ingested_at: datetime,
) -> RawEvent:
    """Insert a raw event into fact_raw_events (Bronze layer).

    event_id and ingested_at are generated by the route handler — never
    derived from client input — to guarantee auditability and uniqueness.
    """
    db_event = RawEvent(
        event_id=event_id,
        ingested_at=ingested_at,
        source=event.source,
        event_type=event.event_type,
        payload=event.payload,
        processed=False,
    )
    db.add(db_event)
    db.commit()
    db.refresh(db_event)
    return db_event


def get_event_by_token(db: Session, token: str) -> RawEvent | None:
    return db.query(RawEvent).filter(
        RawEvent.payload["transaction_token"].astext == token
    ).first()


def is_transaction_token_unique(db: Session, token: str) -> bool:
    return get_event_by_token(db, token) is None


def get_event_by_id(db: Session, event_id: uuid.UUID) -> RawEvent | None:
    return db.query(RawEvent).filter(RawEvent.event_id == event_id).first()


def get_unprocessed_events(db: Session, source: str | None = None, limit: int = 100) -> list[RawEvent]:

    query = db.query(RawEvent).filter(RawEvent.processed == False)
    
    if source:
        query = query.filter(RawEvent.source == source)
    
    return query.limit(limit).all()


def mark_event_as_processed(db: Session, event_id: uuid.UUID) -> bool:
    event = db.query(RawEvent).filter(RawEvent.event_id == event_id).first()
    if not event:
        return False
    event.processed = True
    db.commit()
    return True
